
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.207.78.21:3306/cyyapi?useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: asdvdrge%12
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: none


# ak,sk 这里配置的只是测试。
cyyapi:
  client:
    access-key: 1414
    secret-key: abcdefgh
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://123.207.78.21:8848

