server:
  port: 8090  #网关地址
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://123.207.78.21:8123
          predicates:
            - Path=/api/**
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://123.207.78.21:8848

